services:
  db:
    image: postgres:15.3
    container_name: db
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres-data: