services:
  db:
    image: postgres:15.3
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env